CREATE TABLE demodb.GAME_SALES_UPLOAD_HISTORY
  (
     ID INT(1) NOT NULL AUTO_INCREMENT,
     FILE_NAME  VARCHAR(20) NOT NULL,
	 FILE_RECORDS_COUNT INT(1) NOT NULL,
	 UPLOADED_RECORDS_COUNT INT(1),
     UPLOAD_START_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     UPLOAD_END_TIME TIMESTAMP,
     PRIMARY KEY (ID)
  );

CREATE TABLE demodb.GAME_SALES
  (
     ID         INT(1) NOT NULL,
     GAME_NO    TINYINT(1) NOT NULL,
     GAME_NAME  VARCHAR(20) NOT NULL,
     GAME_CODE  VARCHAR(5) NOT NULL,
     TYPE       TINYINT(1) NOT NULL,
     COST_PRICE DECIMAL(5, 2) NOT NULL,
     PERCENTAGE TINYINT(1) NOT NULL,
     SALE_PRICE DECIMAL(5, 2) NOT NULL,
     SALE_DATE  DATE NOT NULL,
     UPLOAD_HISTORY_ID INT(1) NOT NULL,
     PRIMARY KEY (ID),
     FOREIGN KEY (UPLOAD_HISTORY_ID) REFERENCES demodb.GAME_SALES_UPLOAD_HISTORY(ID),
     KEY IDX_GS_$UHI(UPLOAD_HISTORY_ID)
  );

CREATE INDEX IDX_GS_$SD ON demodb.GAME_SALES (SALE_DATE);

CREATE INDEX IDX_GS_$SP ON demodb.GAME_SALES (SALE_PRICE);

CREATE INDEX IDX_GS_$GN ON demodb.GAME_SALES (GAME_NO);

CREATE TABLE demodb.DAILY_SALES_VOL (
    SALE_DATE DATE NOT NULL,
    GAME_NO  TINYINT(1) NOT NULL,
    SALES_COUNT INT NOT NULL DEFAULT 0,
    PRIMARY KEY(SALE_DATE , GAME_NO),
    KEY IDX_DSV_$GN$SD(GAME_NO, SALE_DATE )
);

CREATE TABLE demodb.DAILY_REVENUE (
    SALE_DATE DATE NOT NULL,
    GAME_NO  TINYINT(1) NOT NULL,
    REVENUE INT NOT NULL DEFAULT 0,
    PRIMARY KEY(SALE_DATE , GAME_NO),
    KEY IDX_DR_$GN$SD(GAME_NO, SALE_DATE )
);

DELIMITER //
CREATE TRIGGER demodb.GAME_SALES_UPLOADED_TRIGGER

AFTER UPDATE ON demodb.GAME_SALES_UPLOAD_HISTORY

FOR EACH ROW

BEGIN

   IF (OLD.UPLOAD_END_TIME IS NULL) THEN

	INSERT INTO demodb.DAILY_SALES_VOL(SALE_DATE,GAME_NO,SALES_COUNT)
	SELECT SALE_DATE, GAME_NO, COUNT(*)
	FROM demodb.GAME_SALES
	WHERE UPLOAD_HISTORY_ID = OLD.ID
	GROUP BY SALE_DATE, GAME_NO;

	INSERT INTO demodb.DAILY_REVENUE(SALE_DATE,GAME_NO,REVENUE)
	SELECT SALE_DATE, GAME_NO, SUM(SALE_PRICE)
	FROM demodb.GAME_SALES
	WHERE UPLOAD_HISTORY_ID = OLD.ID
	GROUP BY SALE_DATE, GAME_NO;

   END IF;

END;//
DELIMITER ;